import fs from 'fs'
import path from 'path'
// "docs": "npm run build && jsdoc ./build -r -d ./docs",
/**
 * @param {string} dir
 * @param {Function} fileCallback
 */
const scanFiles = (dir: string, fileCallback: (filePath: string) => void) => {
  fs.readdirSync(dir).forEach((file) => {
    const fullPath = path.join(dir, file)
    if (fs.statSync(fullPath).isDirectory()) {
      scanFiles(fullPath, fileCallback)
    } else if (file.endsWith('.ts')) {
      fileCallback(fullPath)
    }
  })
}

/** @param {string} filePath */
const addJsDoc = (filePath: string) => {
  const content = fs.readFileSync(filePath, 'utf-8')
  const updatedContent = content.replace(/(function|const|let|var|class) (\w+)(.*?){/g, (match, type, name, params) => {
    const jsDoc = `/**
 * ${name} - autogenerated JSDoc.
 *
${params
  .replace(/[()]/g, '')
  .split(',')
  .map((param: string) => ` * @param ${param.trim()} - description`)
  .join('\n')} * @returns {unknown}
 */
`
    return jsDoc + match
  })
  fs.writeFileSync(filePath, updatedContent, 'utf-8')
}

scanFiles('./src', addJsDoc)
console.log('JSDoc added to TypeScript files.')
